version: "3.0"

services:
  
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  library:
    image: node:20.8-alpine    
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - 8080:3000
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://root:example@mongo:27017/
    command: npm run dev
    depends_on:
      - mongo